### ISSUE TITLE
Добавить папку junit в гитигнор

### ISSUE THREAD

**Issue by swiftizer** [INMalyshev/BMSTU-TEAM-DEV-2024#16]
![Снимок экрана 2024-04-13 в 01 34 35](https://github.com/INMalyshev/BMSTU-TEAM-DEV-2024/assets/78726466/ed4cee3e-e322-4386-8abd-5d06f0131b5e)

После локального прогона тестов возникает такая штука. Я б закинул в гитигнор. Есть противопоказания? 

Ревьюер: @INMalyshev

**Comment by malyshevin** [comment]
Похоже забыл добавить при создании, давай добавим
